module.exports = [{
  id: '4953d960-963f-41e1-a905-f41b026f8760',
  first_name: 'James',
  last_name: 'Smith',
  email: 'contact.jamesh@gmail.com',
  phone_number: '+492222222222',
  address: 'sample street 55',
  pincode: '07743',
  education: 'MBBS from TU Chemnitz, Germany',
  about: 'Dr. James Smith is a Doctor in Chemnitz, Germany and has an experience of 12 years in this field. Dr. James practices at PDeets hospitals Ltd. in Chemnitz, Germany. He completed MBBS from TU Chemnitz in 2012 and MD - general medicine from Government Medical College, India in 2016.',
  licence_no: 'ABCD5558',
  experience: '5',
  image_url: '/doctors/James.png'
},
{
  id: '718b86d7-bdee-4bed-9623-2f32e546e5bc',
  first_name: 'Michael',
  last_name: 'Smith',
  email: 'contact.Michael@gmail.com',
  phone_number: '+492222222222',
  address: 'sample street 58',
  pincode: '07745',
  education: 'MBBS from DDS Institute, India',
  about: 'Dr. Michael Smith is a Doctor in Delhi, Germany and has an experience of 8 years in this field. Dr. Michael practices at PDeets hospitals Ltd. in Chemnitz, Germany. He completed MBBS from MBBS from DDS Institute, India in 2012 and MD - general medicine from Government Medical College, India in 2016.',
  licence_no: 'AJJD5558',
  experience: '8',
  image_url: '/doctors/Michael.png'
},
{
  id: '48d8cc09-e6ed-4627-a6d7-72be0ed9a803',
  first_name: 'Maria',
  last_name: 'Hernandez',
  email: 'contact.Maria@gmail.com',
  phone_number: '+492222222222',
  address: 'sample street 68',
  pincode: '07855',
  education: 'MBBS from LMS Institute, USA',
  about: 'Dr. Maria Hernandez is a Doctor in california, USA and has an experience of 12 years in this field. Dr. Maria practices at PDeets hospitals Ltd. in Chemnitz, Germany. He completed MBBS from MBBS from LMS Institute, USA in 2012 and MD - general medicine from Government Medical College, India in 2016.',
  licence_no: 'MJHHF526',
  experience: '12',
  image_url: '/doctors/Maria.png'
},
{
  id: 'f7d5e280-39f3-4ad8-88da-6cbf5ccc2eda',
  first_name: 'James',
  last_name: 'Johnson',
  email: 'contact.James@gmail.com',
  phone_number: '+492222222222',
  address: 'sample street 78',
  pincode: '07545',
  education: 'MBBS from Cumilla Medical College Hospital, Bangladesh',
  about: 'Dr. James Johnson is a Doctor in Bangladesh and has an experience of 6 years in this field. Dr. James practices at PDeets hospitals Ltd. in Chemnitz, Germany. He completed MBBS from MBBS from Cumilla Medical College Hospital, Bangladesh in 2012 and MD - general medicine from Government Medical College, India in 2016.',
  licence_no: 'LJCW5552',
  experience: '6',
  image_url: '/doctors/James2.png'
},
{
  id: 'dab02153-5929-4545-abeb-87544f68d1bc',
  first_name: 'David',
  last_name: 'Smith',
  email: 'contact.David@gmail.com',
  phone_number: '+492222222222',
  address: 'sample street 79',
  pincode: '07632',
  education: 'MBBS from St. Johns Medical College, India',
  about: 'Dr. David Smith is a Doctor in bangalore, India and has an experience of 8 years in this field. Dr. David practices at PDeets hospitals Ltd. in Chemnitz, Germany. He completed MBBS from MBBS from St. Johns Medical College, India in 2012 and MD - general medicine from Government Medical College, India in 2016.',
  licence_no: 'AJJD5558',
  experience: '8',
  image_url: '/doctors/David.png'
}]
