module.exports = [{
  id: 1,
  first_name: 'Dr. Hans',
  last_name: 'Müller',
  email: 'contact.Hans@gmail.com',
  phone_number: '+492222222222',
  address: 'sample street 55',
  pincode: '07743',
  education: 'MBBS from TU Chemnitz, Germany',
  about: 'Dr. Müller is a Doctor in Chemnitz, Germany and has an experience of 12 years in this field. Dr. Müller practices at PDeets hospitals Ltd. in Chemnitz, Germany. He completed MBBS from TU Chemnitz in 2012 and MD - general medicine from Government Medical College, India in 2016.',
  licence_no: 'ABCD5558',
  experience: '5',
  doctor_speciality: 'Allgemeinmedizin',
  image_url: '/doctors/James.png'
},
{
  id: 2,
  first_name: 'Dr. Martina',
  last_name: 'Muster',
  email: 'contact.Martina@gmail.com',
  phone_number: '+492222222222',
  address: 'sample street 58',
  pincode: '07745',
  education: 'MBBS from DDS Institute, India',
  about: 'Dr. Martina is a Doctor in Delhi, Germany and has an experience of 8 years in this field. Dr. Martina practices at PDeets hospitals Ltd. in Chemnitz, Germany. He completed MBBS from MBBS from DDS Institute, India in 2012 and MD - general medicine from Government Medical College, India in 2016.',
  licence_no: 'AJJD5558',
  experience: '8',
  doctor_speciality: 'Neurologie',
  image_url: '/doctors/Michael.png'
},
{
  id: 3,
  first_name: 'Dr. Bernd',
  last_name: 'Brot',
  email: 'contact.Bernd@gmail.com',
  phone_number: '+492222222222',
  address: 'sample street 68',
  pincode: '07855',
  education: 'MBBS from LMS Institute, USA',
  about: 'Dr. Bernd is a Doctor in california, USA and has an experience of 12 years in this field. Dr. Bernd practices at PDeets hospitals Ltd. in Chemnitz, Germany. He completed MBBS from MBBS from LMS Institute, USA in 2012 and MD - general medicine from Government Medical College, India in 2016.',
  licence_no: 'MJHHF526',
  experience: '12',
  doctor_speciality: 'Allgemeinmedizin',
  image_url: '/doctors/Maria.png'
},
{
  id: 4,
  first_name: 'Dr. Markus',
  last_name: 'Rosenbusch',
  email: 'contact.Markus@gmail.com',
  phone_number: '+492222222222',
  address: 'sample street 78',
  pincode: '07545',
  education: 'MBBS from Cumilla Medical College Hospital, Bangladesh',
  about: 'Dr. Markus is a Doctor in Bangladesh and has an experience of 6 years in this field. Dr. Markus practices at PDeets hospitals Ltd. in Chemnitz, Germany. He completed MBBS from MBBS from Cumilla Medical College Hospital, Bangladesh in 2012 and MD - general medicine from Government Medical College, India in 2016.',
  licence_no: 'LJCW5552',
  experience: '6',
  doctor_speciality: 'Kardiologie',
  image_url: '/doctors/James2.png'
},
{
  id: 5,
  first_name: 'Dr. Anna',
  last_name: 'Petzold',
  email: 'contact.Anna@gmail.com',
  phone_number: '+492222222222',
  address: 'sample street 79',
  pincode: '07632',
  education: 'MBBS from St. Johns Medical College, India',
  about: 'Dr. Anna is a Doctor in bangalore, India and has an experience of 8 years in this field. Dr. Anna practices at PDeets hospitals Ltd. in Chemnitz, Germany. He completed MBBS from MBBS from St. Johns Medical College, India in 2012 and MD - general medicine from Government Medical College, India in 2016.',
  licence_no: 'AJJD5558',
  experience: '8',
  doctor_speciality: 'Allgemeinmedizin',
  image_url: '/doctors/David.png'
},
{
  id: 6,
  first_name: 'Dr. Florian',
  last_name: 'Ruck',
  email: 'contact.Florian@gmail.com',
  phone_number: '+492222222222',
  address: 'sample street 79',
  pincode: '07632',
  education: 'MBBS from St. Johns Medical College, India',
  about: 'Dr. Florian is a Doctor in bangalore, India and has an experience of 8 years in this field. Dr. Florian practices at PDeets hospitals Ltd. in Chemnitz, Germany. He completed MBBS from MBBS from St. Johns Medical College, India in 2012 and MD - general medicine from Government Medical College, India in 2016.',
  licence_no: 'AJJD5558',
  experience: '8',
  doctor_speciality: 'Psychotherapie',
  image_url: '/doctors/David.png'
},
{
  id: 7,
  first_name: 'Dr. Silvia',
  last_name: 'Kleinmüller',
  email: 'contact.Anna@gmail.com',
  phone_number: '+492222222222',
  address: 'sample street 79',
  pincode: '07632',
  education: 'MBBS from St. Johns Medical College, India',
  about: 'Dr. Silvia is a Doctor in bangalore, India and has an experience of 8 years in this field. Dr. Silvia practices at PDeets hospitals Ltd. in Chemnitz, Germany. He completed MBBS from MBBS from St. Johns Medical College, India in 2012 and MD - general medicine from Government Medical College, India in 2016.',
  licence_no: 'AJJD5558',
  experience: '8',
  doctor_speciality: 'Allgemeinmedizin',
  image_url: '/doctors/David.png'
}]
